### ISSUE TITLE
System Update Checklist

### ISSUE THREAD

**Issue by nzoschke** [convox/kernel#118]
While we are still working some kinks out of `convox update`, an update and verify checklist for operators will be very helpful.

- [ ] Check "Version" Parameter in CloudFormation
- [ ] Check kernel and registry image tag version in ECS
- [ ] Check kernel environment by SSHing into the instance and doing a `docker exec convox/kernel env`
- [ ] Deploy a simple app
- [ ] Destroy the simple app
